<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisLevel>preview-recommended</AnalysisLevel>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyName>ytsync</AssemblyName>
    <OutputType>Exe</OutputType>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>false</PublishTrimmed>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
    <PackageReference Include="Google.Apis.Oauth2.v2" Version="1.74.0.1869" />
    <PackageReference Include="Google.Apis.YouTube.v3" Version="1.75.0.4207" />
    <PackageReference Include="Quickenshtein" Version="1.5.1" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
    <PackageReference Include="YoutubeExplode" Version="6.6.0" />
    <PackageReference Include="YoutubeExplode.Converter" Version="6.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Logger/Logger.csproj" />
    <ProjectReference Include="../MusicBrainz/src/Hqub.MusicBrainz/Hqub.MusicBrainz.csproj" />
  </ItemGroup>

</Project>
